### Collection Request
POST https://muyanda.qinsightstech.com/collection

{
    "amount": 1,
    "phone_number": "260974035672"
}

### Transaction status
GET https://muyanda.qinsightstech.com/transaction-status?transaction_ref=9c62ed05-822d-4a52-99e7-6de04d303feb

### KYC Verification
GET https://muyanda.qinsightstech.com/kyc/260974035672
 